RuntimeException уже наследован от Exception и является unchecked